#pragma once

// ast.pb.h is generated by protoc into the build tree.
// CMake adds the correct include path via target_include_directories.
#include "ast.pb.h"
#include <string>

namespace stella {

// Maximum recursion depth before returning a safe terminal token
static constexpr int kMaxDepth = 15;

// ── Top-level ────────────────────────────────────────────────────────────────
std::string ToString(const Program& msg, int depth = 0);

// ── Declarations ─────────────────────────────────────────────────────────────
std::string ToString(const Decl& msg, int depth = 0);
std::string ToString(const DeclFun& msg, int depth = 0);
std::string ToString(const DeclFunGeneric& msg, int depth = 0);
std::string ToString(const DeclTypeAlias& msg, int depth = 0);
std::string ToString(const DeclExceptionType& msg, int depth = 0);
std::string ToString(const DeclExceptionVariant& msg, int depth = 0);

// ── Helpers ───────────────────────────────────────────────────────────────────
std::string ToString(const Annotation& msg, int depth = 0);
std::string ToString(const ParamDecl& msg, int depth = 0);
std::string ToString(const PatternBinding& msg, int depth = 0);
std::string ToString(const Binding& msg, int depth = 0);
std::string ToString(const MatchCase& msg, int depth = 0);
std::string ToString(const LabelledPattern& msg, int depth = 0);
std::string ToString(const RecordFieldType& msg, int depth = 0);
std::string ToString(const VariantFieldType& msg, int depth = 0);

// ── Expressions ───────────────────────────────────────────────────────────────
std::string ToString(const Expr& msg, int depth = 0);

std::string ToString(const ConstInt& msg, int depth = 0);
std::string ToString(const ConstMemory& msg, int depth = 0);
std::string ToString(const Var& msg, int depth = 0);
std::string ToString(const DotRecord& msg, int depth = 0);
std::string ToString(const DotTuple& msg, int depth = 0);
std::string ToString(const If& msg, int depth = 0);
std::string ToString(const Sequence& msg, int depth = 0);
std::string ToString(const Assign& msg, int depth = 0);
std::string ToString(const Let& msg, int depth = 0);
std::string ToString(const LetRec& msg, int depth = 0);
std::string ToString(const Abstraction& msg, int depth = 0);
std::string ToString(const Application& msg, int depth = 0);
std::string ToString(const TypeAbstraction& msg, int depth = 0);
std::string ToString(const TypeApplication& msg, int depth = 0);
std::string ToString(const BinaryOp& msg, int depth = 0);
std::string ToString(const UnaryOp& msg, int depth = 0);
std::string ToString(const TypeAsc& msg, int depth = 0);
std::string ToString(const TypeCast& msg, int depth = 0);
std::string ToString(const Inl& msg, int depth = 0);
std::string ToString(const Inr& msg, int depth = 0);
std::string ToString(const ConsList& msg, int depth = 0);
std::string ToString(const Head& msg, int depth = 0);
std::string ToString(const IsEmpty& msg, int depth = 0);
std::string ToString(const Tail& msg, int depth = 0);
std::string ToString(const ListLiteral& msg, int depth = 0);
std::string ToString(const Succ& msg, int depth = 0);
std::string ToString(const Pred& msg, int depth = 0);
std::string ToString(const IsZero& msg, int depth = 0);
std::string ToString(const NatRec& msg, int depth = 0);
std::string ToString(const Fold& msg, int depth = 0);
std::string ToString(const Unfold& msg, int depth = 0);
std::string ToString(const Ref& msg, int depth = 0);
std::string ToString(const Deref& msg, int depth = 0);
std::string ToString(const Tuple& msg, int depth = 0);
std::string ToString(const Record& msg, int depth = 0);
std::string ToString(const Variant& msg, int depth = 0);
std::string ToString(const Match& msg, int depth = 0);
std::string ToString(const Throw& msg, int depth = 0);
std::string ToString(const TryCatch& msg, int depth = 0);
std::string ToString(const TryCastAs& msg, int depth = 0);
std::string ToString(const TryWith& msg, int depth = 0);
std::string ToString(const Fix& msg, int depth = 0);
std::string ToString(const ParenthesisedExpr& msg, int depth = 0);
std::string ToString(const TerminatingSemicolon& msg, int depth = 0);

// ── Patterns ──────────────────────────────────────────────────────────────────
std::string ToString(const Pattern& msg, int depth = 0);

std::string ToString(const PatternVariant& msg, int depth = 0);
std::string ToString(const PatternInl& msg, int depth = 0);
std::string ToString(const PatternInr& msg, int depth = 0);
std::string ToString(const PatternTuple& msg, int depth = 0);
std::string ToString(const PatternRecord& msg, int depth = 0);
std::string ToString(const PatternList& msg, int depth = 0);
std::string ToString(const PatternCons& msg, int depth = 0);
std::string ToString(const PatternConsPair& msg, int depth = 0);
std::string ToString(const PatternInt& msg, int depth = 0);
std::string ToString(const PatternSucc& msg, int depth = 0);
std::string ToString(const PatternVar& msg, int depth = 0);
std::string ToString(const PatternAsc& msg, int depth = 0);
std::string ToString(const PatternCastAs& msg, int depth = 0);
std::string ToString(const ParenthesisedPattern& msg, int depth = 0);

// ── Types ─────────────────────────────────────────────────────────────────────
std::string ToString(const StellaType& msg, int depth = 0);

std::string ToString(const TypeRef& msg, int depth = 0);
std::string ToString(const TypeSum& msg, int depth = 0);
std::string ToString(const TypeFun& msg, int depth = 0);
std::string ToString(const TypeForAll& msg, int depth = 0);
std::string ToString(const TypeRec& msg, int depth = 0);
std::string ToString(const TypeTuple& msg, int depth = 0);
std::string ToString(const TypeRecord& msg, int depth = 0);
std::string ToString(const TypeVariant& msg, int depth = 0);
std::string ToString(const TypeList& msg, int depth = 0);
std::string ToString(const TypeParens& msg, int depth = 0);

// ── Identifier sanitisation ───────────────────────────────────────────────────
// Maps an arbitrary proto string to a small, collision-friendly identifier.
std::string SanitiseIdent(const std::string& raw);

} // namespace stella
